### ISSUE TITLE
do we want multiple movement commands?

### ISSUE THREAD

**Issue by LegitSi** [Futurama39/my-own-code-stuff-dont-touch-please#4]
Like LU (left up) or UL (up left)
the order would matter as the first command would ALWAYS come before the second command
This would solve the UP problem where UP wouldn't be aided unless it was supported by a second command quickly by another person. (this problem is unique to TPG500, it doesn't happen in TPP)

Additionally, if you want both to happen at the same time, you would add a ! beforehand.
This could be used to get the "they cancel each other out" achievement in a single command.

**Comment by Futurama39** [comment]
I think that in my vision, we'll want the game at about 1/15'th of the speed so we'll pull a key every half second, with that I think we'll easily be able to pull a key every frame so the thing won't be a problem
